---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: docs
  label: Documentation
  create: all
  match: "**/*.md"
  templates:
  - page
- type: heading
  label: Data
- type: directory
  path: _data/sites
  label: Sites
  create: documents
  match: "*"
  new_doc_ext: json
  templates:
  - site
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - ELEVENTY_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx eleventy --serve --output=_site
  publish_command: vuepress build -d .vuepress/dist
  output_directory: ".vuepress/dist"
  preview_command: vuepress build -d .vuepress/dist
