---
label: Site
hide_body: true
fields:
- type: text
  name: name
  label: Name
- type: text
  name: url
  label: URL
- type: text
  name: description
  label: Description
- type: boolean
  name: disabled
  label: Disabled
  default: true
pages:
- _data/sites/11ty.json
